from tkinter import *

root = Tk()

horse_info = LabelFrame(root, text='競走馬情報')
horse_info.pack()

gate_num = Label(horse_info, text='枠番', bg='yellow')
gate_num.grid(row=0, column=0)
horse_name = Label(horse_info, text='馬名')
horse_name.grid(row=0, column=1)
weight = Label(horse_info, text='馬体重')
weight.grid(row=0, column=2)
weight_change = Label(horse_info, text='増減')
weight_change.grid(row=0, column=3)
jockey = Label(horse_info, text='騎手')
jockey.grid(row=1, column=0)
handicap = Label(horse_info, text='負担重量')
handicap.grid(row=1, column=1)
ninki = Label(horse_info, text='人気')
ninki.grid(row=1, column=2)
odds = Label(horse_info, text='単勝')
odds.grid(row=1, column=3)
padock = LabelFrame(root, text='パドック')
padock.pack()

body = LabelFrame(padock, text='馬体')
body.pack()
body_var = StringVar()
body_var.set('n')
fat = Radiobutton(body, text='太め', value='f', variable=body_var)
fat.grid(row=0, column=0)
normal = Radiobutton(body, text='普通', value='n', variable=body_var)
normal.grid(row=0, column=1)
thin = Radiobutton(body, text='細め', value='t', variable=body_var)
thin.grid(row=0, column=2)

walk = LabelFrame(padock, text='歩様')
walk.pack()
walk_var = StringVar()
walk_var.set('c')
outer = Radiobutton(walk, text='外', value='o', variable=walk_var)
outer.grid(row=0, column=0)
center = Radiobutton(walk, text='中', value='c', variable=walk_var)
center.grid(row=0, column=1)
inner = Radiobutton(walk, text='内', value='i', variable=walk_var)
inner.grid(row=0, column=2)
hidume = Checkbutton(walk, text='蹄後向')
hidume.grid(row=1, column=0)
neck = Checkbutton(walk, text='首緩り')
neck.grid(row=1, column=1)

shine = LabelFrame(padock, text='毛艶')
shine.pack()
shine_var = StringVar()
shine_var.set('n')
good = Radiobutton(shine, text='輝く', value='g', variable=shine_var)
good.grid(row=0, column=0)
normal = Radiobutton(shine, text='普通', value='n', variable=shine_var)
normal.grid(row=0, column=1)
bad =  Radiobutton(shine, text='ボサ', value='b', variable=shine_var)
bad.grid(row=0, column=2)

behavior = LabelFrame(padock, text='動作')
behavior.pack()
ear = Checkbutton(behavior, text='耳多動')
ear.grid(row=0, column=0)
amae = Checkbutton(behavior, text='甘え')
amae.grid(row=0, column=1)
monomi = Checkbutton(behavior, text='物見')
monomi.grid(row=0,column=2)

tension = LabelFrame(padock, text='気合')
tension.pack()
tsuru = Checkbutton(tension, text='鶴首')
tsuru.grid(row=0, column=0)
sweat = Checkbutton(tension, text='発汗')
sweat.grid(row=0, column=1)
hyperemia = Checkbutton(tension, text='充血')
hyperemia.grid(row=1, column=0)
two_groom = Checkbutton(tension, text='二人曳')
two_groom.grid(row=1, column=1)

others = LabelFrame(padock, text='その他')
others.pack()
harness = Checkbutton(others, text='馬具')
harness.grid(row=0, column=0)
small_round_hoof = Checkbutton(others, text='小丸蹄')
small_round_hoof.grid(row=0, column=1)
summer_lose = Checkbutton(others, text='夏負')
summer_lose.grid(row=0, column=2)
memo = Entry(others)
memo.grid(row=1, column=1)

save = Button(padock, text='保存')
save.pack()

root.mainloop()
